### ISSUE TITLE
Exploded query parameters are not working

### ISSUE THREAD

**Issue by papegaaij** [microsoft/kiota-abstractions-go#114]
When a query parameter is defined with `"style": "form", "explode": true`, it is supposed to be rendered as a multi-valued parameter that repeats for every value. For example, this parameter:
```
{ "name": "additional",
   "in": "query",
   "description": "Request additional information to be returned for every record.",
   "style": "form",
   "explode": true,
   "schema": {
     "type": "array",
     "items": { "type": "string", "enum": ["audit", "markers", "status"] }
   }
}
```
is supposed to be rendered like `path?additional=audit&additional=markers`, however Kiota renders it like `path?additional=audit,markers`. I've created a pull request that adds a test demonstrating the problem: https://github.com/microsoft/kiota-abstractions-go/pull/113

It seems `std-uritemplate` does render the URI correctly if it is passed a `[]any`, but `AddQueryParameters` converts everything to a `string` to fit it in `RequestInformation.QueryParameters`. I think the type of that field should be changed to `map[string]any` and no conversion should be done. There's one caveat though: `std-uritemplate` only accepts `[]any` as a list parameter, not any other slice type. So for example `[]string{"test1", "test2"}` doesn't work, while `[]any{"test1", "test2"}` does. This may need to be addressed in `std-uritemplate`.

**Comment by baywet** [comment]
Hi @papegaaij
Thanks for reporting this and for opening a pull request.
We do have an implementation drift since [dotnet is Dictionary<string,object>](https://github.com/microsoft/kiota-abstractions-dotnet/blob/dc816a517f5b8348fa77429b9a1539ef00a2d135/src/RequestInformation.cs#L99)
The challenge with fixing this issue is that changing the type of the property is binary breaking, which goes against our support policy.
The workaround would probably to:
1. revert the type change
2. mark the property as obsolete
3. introduce a new property "QueryParametersAny" (or with a better name)
4. introduce a GetQueryParameters method in request information that would generate a union the "Old" property and the new one.
5. map all code in kiota libraries that inserts query parameters to the new property
6. map all code in kiota libraries that reads query parameters to the new method
7. in a v2, clean all of this up

Thoughts? Do you think you could amend your pull request to reflect this?

**Comment by papegaaij** [comment]
I don't think your approach will work. `RequestInformation` is an exported type, as is the `QueryParameters` field. Consumers of this API will thus be operating on the internals of the code. It would have been better if `RequestInformation` would not have been exported. Adding a new method to read the query parameters will break code not using this new method at runtime.

I've decided to take a bit of different route. I've added a new field that contains the actual slice value for the exploded parameters. Values in this map override values in the other map, but the other map is still available and still works the same way. This should keep both binary as runtime compatibility in most cases. The only change is when someone uses `AddQueryParameters` to add a slice and then updates the `QueryParameters` field directly, but I would consider that bad behavior.
